[package]
name = "DePayTokenObjects"
version = "1.0.0"

[addresses]
std = "0x1"
depay_std = "0x1"
depay_framework = "0x1"
depay_token_objects = "0x4"

[dependencies]
MoveStdlib = { local = "../move-stdlib" }
DePayFramework = { local = "../depay-framework"}
