[package]
name = "DePayStdlib"
version = "1.0.0"

[addresses]
std = "0x1"
depay_std = "0x1"
depay_framework = "0x1"
Extensions = "0x1" # For Prover to instantiate `{{Ext}}` in prelude.

[dependencies]
MoveStdlib = { local = "../move-stdlib" }
